### ISSUE TITLE
Running suite of test cases shows report only for 1 suite.

### ISSUE THREAD

**Issue by drptbl** [sharadJay/nightwatch-allure-adapter#3]
Hello!

First of all - thanks for this great plugin. I was looking for something like this from ages.

I'm having an issue with it:
- When I run whole suite of test cases (so for example I have 3 suites with tests), after my report is parsed with `allure generate` I see results only for 1 test case (first one).

I can see that *.json file generated by yours plugin contains proper data, but after it's being parsed into a report it's not looking good. Please look at screenshots - on the images you can see only 1 test case suite (when there should be 3) and you can also see that *.json file contains them (572 tests passed for example, when report shows only 6.

What is the problem? Can you help?

Thank you!

![screen shot 2015-11-05 at 15 37 13](https://cloud.githubusercontent.com/assets/8177587/10971221/83b832c6-83d3-11e5-88a3-54f925294c5b.png)
![screen shot 2015-11-05 at 15 37 27](https://cloud.githubusercontent.com/assets/8177587/10971228/8b4acfe4-83d3-11e5-8a47-6c4e6a5ee143.png)

I can provide more informations if needed.

Those tests are run and parsed with Jenkins (Allure Jenkins Plugin).
1.4.19 - allure command line version.

**Comment by drptbl** [comment]
What versions do you use if this works for you?

**Comment by drptbl** [comment]
If you need *.json file generated report, I can provide it but privately via e-mail or smth.

**Comment by sharadJay** [comment]
Are you running multiple suites at one time ? Can you also share what command you are using to run tests ?

**Comment by drptbl** [comment]
Yeah, I'm running multiple suites at one time. (my `tests` folder contains suites, some of them has `prod` tag, each of them has some count of tests which are running)
I'm using this command to run my tests:
`nightwatch -c ./Nightwatch.json --env phantom --suiteRetries 2 --tag=prod`

Thanks for fast reply! I would love to fix this, so I can provide all informations you need :+1:.
I bet this is working properly for you, so it's some kind of problem on my side. Any suggestions?
Thanks!

P.S
I've sent you *.json report which is generated by your plugin (and then it's parsed by allure report itself I guess?) into your's gmail box which I found on npmjs website. Maybe it helps somehow.

**Comment by sharadJay** [comment]
@drptbl There was a bug that I resolved in 1.1.9, can you please update and see if it solves your problem ?

**Comment by drptbl** [comment]
Awesome, gonna check this today!

**Comment by drptbl** [comment]
This issue has been fixed, thank you! :)

Probably found another bug, but I have to investigate this. I'm going to create new ticket.

Thanks!
Jacob.
